import assert from "node:assert/strict";
import { once } from "node:events";
import { DatabaseSync } from "node:sqlite";
import { mkdtemp, readFile, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import test from "node:test";
import { Worker } from "node:worker_threads";

const generated = await readFile(new URL("../src/generated/worker-source.vel", import.meta.url), "utf8");
const artifact = await readFile(new URL("../dist/index.js", import.meta.url), "utf8");
const match = /^\/\/\/ Generated by the SQLite Worker resource pipeline\. Do not edit\.\nexport const sqliteWorkerSourceFormatVersion = (\d+)\nexport const sqliteWorkerSource = (.+)\n$/u.exec(generated);
assert.ok(match, "generated SQLite Worker source module has an invalid shape");

function decodeVelarStringLiteral(literal) {
  assert.ok(literal.startsWith("`") && literal.endsWith("`"), "generated Worker source must use a Velar raw string");
  let decoded = "";
  for (let index = 1; index < literal.length - 1; index += 1) {
    const character = literal[index];
    if (character !== "\\") {
      decoded += character;
      continue;
    }

    index += 1;
    const escape = literal[index];
    if (escape === "u") {
      assert.equal(literal[index + 1], "{", "generated Worker source has an invalid Unicode escape");
      const closingBrace = literal.indexOf("}", index + 2);
      assert.notEqual(closingBrace, -1, "generated Worker source has an unterminated Unicode escape");
      const hexadecimal = literal.slice(index + 2, closingBrace);
      assert.match(hexadecimal, /^[0-9a-f]+$/u, "generated Worker source has an invalid Unicode escape");
      decoded += String.fromCodePoint(Number.parseInt(hexadecimal, 16));
      index = closingBrace;
      continue;
    }

    const escapes = { "\\": "\\", "`": "`", b: "\b", f: "\f", n: "\n", r: "\r", t: "\t" };
    assert.ok(Object.hasOwn(escapes, escape), `generated Worker source has an unsupported escape: \\${escape}`);
    decoded += escapes[escape];
  }
  return decoded;
}

const resource = { formatVersion: Number(match[1]), source: decodeVelarStringLiteral(match[2]) };

function workerUrl() {
  return new URL(`data:text/javascript;charset=utf-8,${encodeURIComponent(resource.source)}`);
}

test("the frozen artifact closes the Worker resource without an ambient loader", () => {
  assert.doesNotMatch(artifact, /globalThis\.require/u);
  assert.doesNotMatch(artifact, /\b(?:from|import\()\s*["']sqlite3-parser["']/u);
  assert.doesNotMatch(artifact, /\beval\s*:\s*true\b/u);
  assert.match(artifact, /data:text\/javascript/u);
});

test("generated SQLite Worker owns its parser and refuses the main thread", async () => {
  assert.equal(resource.formatVersion, 1);
  assert.equal(typeof resource.source, "string");
  assert.doesNotMatch(resource.source, /(?:from|import\(|require\()\s*["']sqlite3-parser["']/u);
  await assert.rejects(import(workerUrl().href), /SQLite runtime must execute inside its owned Worker/u);
});

test("generated SQLite Worker rejects multiple statements inside its isolated runtime", async (context) => {
  const worker = new Worker(workerUrl(), {
    type: "module",
    workerData: {
      path: ":memory:",
      busyTimeoutMilliseconds: 2000,
      maxRows: 100,
      maxResultBytes: 1024 * 1024,
      statementCacheCapacity: 16,
      journalMode: null,
      readOnly: false,
    },
  });
  context.after(() => worker.terminate());
  assert.ok(worker.threadId > 0);

  const [ready] = await once(worker, "message");
  assert.deepEqual(ready, { kind: "ready" });

  const rejected = once(worker, "message");
  worker.postMessage({
    id: 1,
    operation: "execute",
    fragments: ["CREATE TABLE hidden (value INTEGER); DROP TABLE hidden"],
    params: [],
  });
  const [response] = await rejected;
  assert.equal(response.kind, "response");
  assert.equal(response.id, 1);
  assert.equal(response.error?.sqliteCode, "SQLITE_INPUT");

  const closed = once(worker, "message");
  const exited = once(worker, "exit");
  worker.postMessage({ id: 2, operation: "close", fragments: [""], params: [] });
  assert.deepEqual((await closed)[0], { kind: "response", id: 2, value: null });
  assert.equal((await exited)[0], 0);
});

test("generated SQLite Worker closes a partially initialized database before exiting", async (context) => {
  const directory = await mkdtemp(join(tmpdir(), "velarscript-sqlite-worker-init-"));
  const path = join(directory, "initialization.sqlite");
  try {
    const worker = new Worker(workerUrl(), {
      type: "module",
      workerData: {
        path,
        busyTimeoutMilliseconds: 2000,
        maxRows: 100,
        maxResultBytes: 1024 * 1024,
        statementCacheCapacity: 16,
        journalMode: "'",
        readOnly: false,
      },
    });
    context.after(() => worker.terminate());
    const [ready] = await once(worker, "message");
    assert.equal(ready.kind, "ready");
    assert.equal(ready.error?.operation, "open");
    assert.equal((await once(worker, "exit"))[0], 0);

    const reopened = new DatabaseSync(path);
    reopened.exec("CREATE TABLE cleanup_proof (value INTEGER)");
    reopened.close();
  } finally {
    await rm(directory, { recursive: true, force: true });
  }
});
