#!/usr/bin/env node

import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { build } from "esbuild";

const packageRoot = resolve(fileURLToPath(new URL("..", import.meta.url)));
const workerEntry = resolve(packageRoot, "worker/sqlite-worker.mjs");
const output = resolve(packageRoot, "src/generated/worker-source.vel");
const notice = await readFile(resolve(packageRoot, "THIRD_PARTY_NOTICES.md"), "utf8");
const arguments_ = process.argv.slice(2);
const check = arguments_.length === 1 && arguments_[0] === "--check";

function velarStringLiteral(value) {
  let escaped = "";
  for (const character of value) {
    switch (character) {
      case "\\": escaped += "\\\\"; break;
      case "`": escaped += "\\`"; break;
      case "$": escaped += "\\u{24}"; break;
      case "\b": escaped += "\\b"; break;
      case "\f": escaped += "\\f"; break;
      case "\n": escaped += "\\n"; break;
      case "\r": escaped += "\\r"; break;
      case "\t": escaped += "\\t"; break;
      default: {
        const codePoint = character.codePointAt(0);
        escaped += codePoint < 0x20
          ? `\\u{${codePoint.toString(16)}}`
          : character;
      }
    }
  }
  return `\`${escaped}\``;
}

if (arguments_.length > (check ? 1 : 0)) {
  throw new Error("Usage: node scripts/generate-worker.mjs [--check]");
}

const banner = `/*!\n${notice.trimEnd().split("\n").map((line) => line.length === 0 ? " *" : ` * ${line}`).join("\n")}\n */`;
const result = await build({
  absWorkingDir: packageRoot,
  entryPoints: [workerEntry],
  bundle: true,
  platform: "node",
  format: "esm",
  target: "node24",
  external: ["node:*"],
  minify: true,
  legalComments: "none",
  banner: { js: banner },
  metafile: true,
  write: false,
  logLevel: "silent",
});

if (result.outputFiles.length !== 1) throw new Error("SQLite Worker generation produced an unexpected output set");
const externalImports = Object.values(result.metafile.outputs)
  .flatMap((entry) => entry.imports)
  .filter((entry) => entry.external)
  .map((entry) => entry.path);
const unexpectedImports = externalImports.filter((specifier) => !specifier.startsWith("node:"));
if (unexpectedImports.length > 0) {
  throw new Error(`SQLite Worker retained external package imports: ${[...new Set(unexpectedImports)].sort().join(", ")}`);
}

const generated = [
  "/// Generated by the SQLite Worker resource pipeline. Do not edit.",
  "export const sqliteWorkerSourceFormatVersion = 1",
  `export const sqliteWorkerSource = ${velarStringLiteral(result.outputFiles[0].text)}`,
  "",
].join("\n");
const existing = await readFile(output, "utf8").catch((error) => {
  if (error?.code === "ENOENT") return null;
  throw error;
});

if (existing === generated) {
  process.stdout.write("SQLite Worker source module is current.\n");
} else if (check) {
  throw new Error("SQLite Worker source module is stale; run npm run generate:worker --workspace @velarscript-labs/sqlite");
} else {
  await mkdir(dirname(output), { recursive: true });
  await writeFile(output, generated, "utf8");
  process.stdout.write(`Generated SQLite Worker source module (${String(result.outputFiles[0].contents.byteLength)} bytes).\n`);
}
