#!/usr/bin/env node

import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { build } from "esbuild";

const packageRoot = resolve(fileURLToPath(new URL("..", import.meta.url)));
const runtimeEntry = resolve(packageRoot, "scripts/msgpack-runtime-entry.mjs");
const output = resolve(packageRoot, "src/generated/runtime.vel");
const notice = await readFile(resolve(packageRoot, "THIRD_PARTY_NOTICES.md"), "utf8");
const arguments_ = process.argv.slice(2);
const check = arguments_.length === 1 && arguments_[0] === "--check";

if (arguments_.length > (check ? 1 : 0)) {
  throw new Error("Usage: node scripts/generate-runtime.mjs [--check]");
}

const dynamicTypedArrayLookup = [
  "let glbl = typeof globalThis === 'object' ? globalThis : window;",
  "currentExtensions[0x74] = (data) => {",
  "\tlet typeCode = data[0];",
  "\t// we always have to slice to get a new ArrayBuffer that is aligned",
  "\tlet buffer = Uint8Array.prototype.slice.call(data, 1).buffer;",
  "",
  "\tlet typedArrayName = typedArrays[typeCode];",
  "\tif (!typedArrayName) {",
  "\t\tif (typeCode === 16) return buffer;",
  "\t\tif (typeCode === 17) return new DataView(buffer);",
  "\t\tthrow new Error('Could not find typed array for code ' + typeCode);",
  "\t}",
  "\treturn new glbl[typedArrayName](buffer);",
  "};",
].join("\n");

const closedTypedArrayLookup = [
  "function typedArrayConstructor(typeCode) {",
  "\tswitch (typeCode) {",
  "\t\tcase 0: return Int8Array;",
  "\t\tcase 1: return Uint8Array;",
  "\t\tcase 2: return Uint8ClampedArray;",
  "\t\tcase 3: return Int16Array;",
  "\t\tcase 4: return Uint16Array;",
  "\t\tcase 5: return Int32Array;",
  "\t\tcase 6: return Uint32Array;",
  "\t\tcase 7: return Float32Array;",
  "\t\tcase 8: return Float64Array;",
  "\t\tcase 9: return BigInt64Array;",
  "\t\tcase 10: return BigUint64Array;",
  "\t\tdefault: return null;",
  "\t}",
  "}",
  "currentExtensions[0x74] = (data) => {",
  "\tlet typeCode = data[0];",
  "\t// we always have to slice to get a new ArrayBuffer that is aligned",
  "\tlet buffer = Uint8Array.prototype.slice.call(data, 1).buffer;",
  "",
  "\tlet Constructor = typedArrayConstructor(typeCode);",
  "\tif (!Constructor) {",
  "\t\tif (typeCode === 16) return buffer;",
  "\t\tif (typeCode === 17) return new DataView(buffer);",
  "\t\tthrow new Error('Could not find typed array for code ' + typeCode);",
  "\t}",
  "\treturn new Constructor(buffer);",
  "};",
].join("\n");

const closeMsgpackrRuntime = {
  name: "close-msgpackr-runtime",
  setup(context) {
    context.onLoad({ filter: /[/\\]msgpackr[/\\]unpack\.js$/ }, async ({ path }) => {
      const source = await readFile(path, "utf8");
      const first = source.indexOf(dynamicTypedArrayLookup);
      const last = source.lastIndexOf(dynamicTypedArrayLookup);
      if (first < 0 || first !== last) {
        throw new Error("Pinned msgpackr unpack source no longer has the one reviewed typed-array lookup");
      }
      return {
        contents: source.replace(dynamicTypedArrayLookup, closedTypedArrayLookup),
        loader: "js",
      };
    });
  },
};

const banner = `/*!\n${notice.trimEnd().split("\n").map((line) => line.length === 0 ? " *" : ` * ${line}`).join("\n")}\n */`;
const result = await build({
  absWorkingDir: packageRoot,
  entryPoints: [runtimeEntry],
  bundle: true,
  platform: "browser",
  format: "esm",
  target: "es2022",
  supported: { "template-literal": false },
  minify: true,
  treeShaking: true,
  legalComments: "none",
  banner: { js: banner },
  metafile: true,
  plugins: [closeMsgpackrRuntime],
  write: false,
  logLevel: "silent",
});

if (result.outputFiles.length !== 1) throw new Error("MessagePack runtime generation produced an unexpected output set");
const externalImports = Object.values(result.metafile.outputs)
  .flatMap((entry) => entry.imports)
  .filter((entry) => entry.external)
  .map((entry) => entry.path);
if (externalImports.length > 0) {
  throw new Error(`MessagePack runtime retained external imports: ${[...new Set(externalImports)].sort().join(", ")}`);
}

const javascript = result.outputFiles[0].text.trimEnd();
const generated = [
  "/// Generated by the MessagePack ESM runtime pipeline. Do not edit.",
  "extern js`",
  ...javascript.split("\n").map((line) => `    ${line}`),
  "`:",
  "    export def packNative(value: unknown) -> unknown",
  "    export def unpackNative(value: unknown) -> unknown",
  "",
  "export def pack(value: unknown) -> unknown: return packNative(value)",
  "export def unpack(value: unknown) -> unknown: return unpackNative(value)",
  "",
].join("\n");
const existing = await readFile(output, "utf8").catch((error) => {
  if (error?.code === "ENOENT") return null;
  throw error;
});

if (existing === generated) {
  process.stdout.write("MessagePack embedded ESM runtime is current.\n");
} else if (check) {
  throw new Error("MessagePack ESM runtime is stale; run npm run generate:runtime --workspace @velarscript-labs/msgpack");
} else {
  await mkdir(dirname(output), { recursive: true });
  await writeFile(output, generated, "utf8");
  process.stdout.write(`Generated MessagePack embedded ESM runtime (${String(result.outputFiles[0].contents.byteLength)} JavaScript bytes).\n`);
}
